.TH ctx 1 "2022 August" "ctx 1.0"

.SH NAME
ctx \- Convert files to use xrdb variables

.SH SYNOPSIS

.SY ctx
.RI [ path to original_file ]
.RI [ path to output_file ]

.SH DESCRIPTION

is a POSIX script that helps you convert files
to use xrdb variables.

.SH BUGS
No known bugs.

.SH AUTHOR
Originally written by joao-vitor-sr.
.IR < https://github.com/joao-vitor-sr >

SH BUGS
Report bugs on github
.IR < https://github.com/joao-vitor-sr/ctx/issues >
